name: Man10AuctionHouse
version: @version@
main: ltotj.minecraft.man10auctionhouse.Main
depend:
  - Vault
api-version: 1.17
commands:
  mah:
    usage: ""
  mahop:
    usage: "OP用"
  mbid:
    usage: "入札用"

permissions:
  man10auction.user:
    default: true
  man10auction.op:
    default: op
    children:
      man10auction.user: true